name: theme_mode_changer
description: "change or switch theme mode in your app."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/theme_mode_changer

version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  june: ^0.8.8 #@add
  june_flow_util: ^0.8.19

dev_dependencies:
  config_theme: ^0.0.1+1 #@add
  flutter_test:
    sdk: flutter
  june_vm_module: ^1.0.5

flutter:
  assets:
    - assets/module/theme_mode_changer/
  uses-material-design: true