name: theme_mode_changer
description: "change or switch theme mode in your app."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/theme_mode_changer

version: 1.0.5

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june:  #@add
  june_flow_util:

dev_dependencies:
  config_theme: #@add
  flutter_test:
    sdk: flutter
  june_vm_module:

flutter:
  assets:
    - assets/module/theme_mode_changer/
  uses-material-design: true